// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EEqRi1sJYMkZv0RnW2_jqAIx4-RUEzQ',
    appId: '1:297742578820:web:61ec15fd74f909e787fed1',
    messagingSenderId: '297742578820',
    projectId: 'absen-93a9c',
    authDomain: 'absen-93a9c.firebaseapp.com',
    storageBucket: 'absen-93a9c.appspot.com',
    measurementId: 'G-58VBTMHW4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpMXYi16CjuT55SE3dV7iPcdmPdUS0WI',
    appId: '1:297742578820:android:d40f58efe1dc58c587fed1',
    messagingSenderId: '297742578820',
    projectId: 'absen-93a9c',
    storageBucket: 'absen-93a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4prqmsVYEBFslhiMuwOAMY6t9aUykBJs',
    appId: '1:297742578820:ios:e82805171aac6d1987fed1',
    messagingSenderId: '297742578820',
    projectId: 'absen-93a9c',
    storageBucket: 'absen-93a9c.appspot.com',
    iosClientId: '297742578820-k1d39jvnn0v5jcv8gntnha5pssoefu1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4prqmsVYEBFslhiMuwOAMY6t9aUykBJs',
    appId: '1:297742578820:ios:e82805171aac6d1987fed1',
    messagingSenderId: '297742578820',
    projectId: 'absen-93a9c',
    storageBucket: 'absen-93a9c.appspot.com',
    iosClientId: '297742578820-k1d39jvnn0v5jcv8gntnha5pssoefu1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiFlutter',
  );
}
